name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      # TODO: This is broken with `basename` -- it fork explodes
      # - name: asdf_plugin_test
      #   uses: asdf-vm/actions/plugin-test@v3
      #   with:
      #     command: coreutils --help
      - name: echo
        run: echo "Hello, world!"
